#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/datajpa
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        # show_sql: true
#        format_sql: true

spring:
  thymeleaf:
    prefix : classpath:templates/
    suffix : .html
    cache : false
  jpa:
    hibernate:
      ddl-auto: create
    # show-sql: true # DDL 출력

logging.level:
  org.hibernate.SQL: debug
  # org.hibernate.type: trace